name: actions

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          # プライベートリポジトリを指定
          repository: ko1ke/webpack-sass
          # checkout 先のパスを指定
          path: ./private-repo-example
          # 秘密鍵を指定
          token: ${{ secrets.TOKEN }}    
